"""create_all_tables

Revision ID: 1c13f8bc920f
Revises: 
Create Date: 2026-03-03 01:16:03.563825

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '1c13f8bc920f'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('clients',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company_name', sa.String(length=255), nullable=False),
    sa.Column('payment_terms', sa.Integer(), nullable=False, comment='Net payment days: 30, 45, 60, or 90'),
    sa.Column('tax_percentage', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('discount_percentage', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('auto_invoice', sa.Boolean(), nullable=False, comment='If True, invoices are created automatically when delivery is recorded'),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_clients_company_name'), 'clients', ['company_name'], unique=False)
    op.create_table('vendors',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company_name', sa.String(length=255), nullable=False),
    sa.Column('contact_name', sa.String(length=255), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('phone', sa.String(length=50), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('client_addresses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('client_id', sa.Integer(), nullable=False),
    sa.Column('label', sa.String(length=255), nullable=False, comment="Friendly label, e.g. 'Main Warehouse', 'HQ Office'"),
    sa.Column('address_line_1', sa.String(length=255), nullable=False),
    sa.Column('address_line_2', sa.String(length=255), nullable=True),
    sa.Column('city', sa.String(length=100), nullable=False),
    sa.Column('state', sa.String(length=100), nullable=False),
    sa.Column('zip_code', sa.String(length=20), nullable=False),
    sa.Column('country', sa.String(length=100), nullable=False),
    sa.Column('is_default', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_client_addresses_client_id'), 'client_addresses', ['client_id'], unique=False)
    op.create_table('client_contacts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('client_id', sa.Integer(), nullable=False),
    sa.Column('contact_type', sa.Enum('MAIN', 'SECONDARY', 'ACCOUNTING', name='contact_type', create_constraint=True), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('phone', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_client_contacts_client_id'), 'client_contacts', ['client_id'], unique=False)
    op.create_table('skus',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sku_code', sa.String(length=100), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('default_vendor_id', sa.Integer(), nullable=True),
    sa.Column('track_inventory', sa.Boolean(), nullable=False, comment='Enable running inventory count for stocked SKUs'),
    sa.Column('inventory_count', sa.Integer(), nullable=False, comment='Current available units (only meaningful when track_inventory=True)'),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['default_vendor_id'], ['vendors.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_skus_sku_code'), 'skus', ['sku_code'], unique=True)
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('full_name', sa.String(length=255), nullable=False),
    sa.Column('role', sa.Enum('ADMIN', 'ACCOUNT_MANAGER', 'VENDOR', name='user_role', create_constraint=True), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('vendor_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['vendor_id'], ['vendors.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('audit_log',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True, comment='NULL for unauthenticated or pure-system actions'),
    sa.Column('action', sa.String(length=100), nullable=False, comment="Verb describing the action, e.g. 'create_client', 'update_po_status'"),
    sa.Column('entity_type', sa.String(length=100), nullable=False, comment="Table/model name, e.g. 'client', 'sales_order'"),
    sa.Column('entity_id', sa.Integer(), nullable=True, comment='Primary key of the affected record'),
    sa.Column('details', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment='Arbitrary JSON payload with before/after values, inputs, etc.'),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('source', sa.Enum('UI', 'AI', 'SYSTEM', name='event_source', create_constraint=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audit_log_created_at'), 'audit_log', ['created_at'], unique=False)
    op.create_table('client_assignments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('client_id', sa.Integer(), nullable=False),
    sa.Column('assigned_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'client_id', name='uq_user_client_assignment')
    )
    op.create_index(op.f('ix_client_assignments_client_id'), 'client_assignments', ['client_id'], unique=False)
    op.create_index(op.f('ix_client_assignments_user_id'), 'client_assignments', ['user_id'], unique=False)
    op.create_table('sales_orders',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('order_number', sa.String(length=100), nullable=False),
    sa.Column('client_id', sa.Integer(), nullable=False),
    sa.Column('ship_to_address_id', sa.Integer(), nullable=True),
    sa.Column('status', sa.Enum('PENDING', 'PARTIAL_DELIVERED', 'DELIVERED', name='so_status', create_constraint=True), nullable=False),
    sa.Column('original_pdf_url', sa.String(length=500), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['ship_to_address_id'], ['client_addresses.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sales_orders_client_id'), 'sales_orders', ['client_id'], unique=False)
    op.create_index(op.f('ix_sales_orders_order_number'), 'sales_orders', ['order_number'], unique=True)
    op.create_index(op.f('ix_sales_orders_status'), 'sales_orders', ['status'], unique=False)
    op.create_table('sku_vendors',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sku_id', sa.Integer(), nullable=False),
    sa.Column('vendor_id', sa.Integer(), nullable=False),
    sa.Column('is_default', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['sku_id'], ['skus.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['vendor_id'], ['vendors.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('sku_id', 'vendor_id', name='uq_sku_vendor')
    )
    op.create_index(op.f('ix_sku_vendors_sku_id'), 'sku_vendors', ['sku_id'], unique=False)
    op.create_index(op.f('ix_sku_vendors_vendor_id'), 'sku_vendors', ['vendor_id'], unique=False)
    op.create_table('tier_pricing',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sku_id', sa.Integer(), nullable=False),
    sa.Column('min_qty', sa.Integer(), nullable=False),
    sa.Column('max_qty', sa.Integer(), nullable=True, comment='NULL = unlimited (highest tier)'),
    sa.Column('unit_price', sa.Numeric(precision=18, scale=2), nullable=False, comment='Price per unit in USD'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['sku_id'], ['skus.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tier_pricing_sku_id'), 'tier_pricing', ['sku_id'], unique=False)
    op.create_table('purchase_orders',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('po_number', sa.String(length=100), nullable=False),
    sa.Column('sales_order_id', sa.Integer(), nullable=False),
    sa.Column('vendor_id', sa.Integer(), nullable=False),
    sa.Column('shipment_type', sa.Enum('DROP_SHIP', 'IN_HOUSE', name='shipment_type', create_constraint=True), nullable=False),
    sa.Column('status', sa.Enum('IN_PRODUCTION', 'PACKED_AND_SHIPPED', 'READY_FOR_PICKUP', 'DELIVERED', name='po_status', create_constraint=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['sales_order_id'], ['sales_orders.id'], ),
    sa.ForeignKeyConstraint(['vendor_id'], ['vendors.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_purchase_orders_po_number'), 'purchase_orders', ['po_number'], unique=True)
    op.create_index(op.f('ix_purchase_orders_sales_order_id'), 'purchase_orders', ['sales_order_id'], unique=False)
    op.create_index(op.f('ix_purchase_orders_vendor_id'), 'purchase_orders', ['vendor_id'], unique=False)
    op.create_table('so_lines',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sales_order_id', sa.Integer(), nullable=False),
    sa.Column('sku_id', sa.Integer(), nullable=False),
    sa.Column('line_number', sa.Integer(), nullable=False, comment='Position of this line within the Sales Order (1-based)'),
    sa.Column('ordered_qty', sa.Integer(), nullable=False),
    sa.Column('unit_price', sa.Numeric(precision=18, scale=2), nullable=False, comment='Locked at SO creation from tier pricing – never changes'),
    sa.Column('delivered_qty', sa.Integer(), nullable=False, comment='Sum of all fulfillment events for this line'),
    sa.Column('invoiced_qty', sa.Integer(), nullable=False, comment='Sum of all invoice line quantities (Milestone 2)'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['sales_order_id'], ['sales_orders.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['sku_id'], ['skus.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('sales_order_id', 'line_number', name='uq_so_line_number')
    )
    op.create_index(op.f('ix_so_lines_sales_order_id'), 'so_lines', ['sales_order_id'], unique=False)
    op.create_table('po_lines',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('purchase_order_id', sa.Integer(), nullable=False),
    sa.Column('so_line_id', sa.Integer(), nullable=False),
    sa.Column('sku_id', sa.Integer(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['purchase_order_id'], ['purchase_orders.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['sku_id'], ['skus.id'], ),
    sa.ForeignKeyConstraint(['so_line_id'], ['so_lines.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_po_lines_purchase_order_id'), 'po_lines', ['purchase_order_id'], unique=False)
    op.create_table('fulfillment_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('so_line_id', sa.Integer(), nullable=False),
    sa.Column('po_line_id', sa.Integer(), nullable=True),
    sa.Column('quantity', sa.Integer(), nullable=False, comment='Number of units delivered in this event'),
    sa.Column('recorded_by', sa.Integer(), nullable=False),
    sa.Column('source', sa.Enum('UI', 'AI', 'SYSTEM', name='event_source', create_constraint=True), nullable=False, comment='Whether recorded via UI or AI chat'),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['po_line_id'], ['po_lines.id'], ),
    sa.ForeignKeyConstraint(['recorded_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['so_line_id'], ['so_lines.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_fulfillment_events_created_at'), 'fulfillment_events', ['created_at'], unique=False)
    op.create_index(op.f('ix_fulfillment_events_so_line_id'), 'fulfillment_events', ['so_line_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_fulfillment_events_so_line_id'), table_name='fulfillment_events')
    op.drop_index(op.f('ix_fulfillment_events_created_at'), table_name='fulfillment_events')
    op.drop_table('fulfillment_events')
    op.drop_index(op.f('ix_po_lines_purchase_order_id'), table_name='po_lines')
    op.drop_table('po_lines')
    op.drop_index(op.f('ix_so_lines_sales_order_id'), table_name='so_lines')
    op.drop_table('so_lines')
    op.drop_index(op.f('ix_purchase_orders_vendor_id'), table_name='purchase_orders')
    op.drop_index(op.f('ix_purchase_orders_sales_order_id'), table_name='purchase_orders')
    op.drop_index(op.f('ix_purchase_orders_po_number'), table_name='purchase_orders')
    op.drop_table('purchase_orders')
    op.drop_index(op.f('ix_tier_pricing_sku_id'), table_name='tier_pricing')
    op.drop_table('tier_pricing')
    op.drop_index(op.f('ix_sku_vendors_vendor_id'), table_name='sku_vendors')
    op.drop_index(op.f('ix_sku_vendors_sku_id'), table_name='sku_vendors')
    op.drop_table('sku_vendors')
    op.drop_index(op.f('ix_sales_orders_status'), table_name='sales_orders')
    op.drop_index(op.f('ix_sales_orders_order_number'), table_name='sales_orders')
    op.drop_index(op.f('ix_sales_orders_client_id'), table_name='sales_orders')
    op.drop_table('sales_orders')
    op.drop_index(op.f('ix_client_assignments_user_id'), table_name='client_assignments')
    op.drop_index(op.f('ix_client_assignments_client_id'), table_name='client_assignments')
    op.drop_table('client_assignments')
    op.drop_index(op.f('ix_audit_log_created_at'), table_name='audit_log')
    op.drop_table('audit_log')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_skus_sku_code'), table_name='skus')
    op.drop_table('skus')
    op.drop_index(op.f('ix_client_contacts_client_id'), table_name='client_contacts')
    op.drop_table('client_contacts')
    op.drop_index(op.f('ix_client_addresses_client_id'), table_name='client_addresses')
    op.drop_table('client_addresses')
    op.drop_table('vendors')
    op.drop_index(op.f('ix_clients_company_name'), table_name='clients')
    op.drop_table('clients')
    # ### end Alembic commands ###

