"""add_date_fields_to_so_and_po

Revision ID: 846f1e5b4df9
Revises: 1c13f8bc920f
Create Date: 2026-03-11 17:54:02.450643

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '846f1e5b4df9'
down_revision: Union[str, None] = '1c13f8bc920f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('po_lines', sa.Column('due_date', sa.Date(), nullable=True, comment='Per-line due date (inherited from the originating SO line)'))
    op.add_column('po_lines', sa.Column('expected_ship_date', sa.Date(), nullable=True, comment='Per-line expected ship date (vendor can update individually)'))
    op.add_column('po_lines', sa.Column('expected_arrival_date', sa.Date(), nullable=True, comment='Per-line expected arrival date (vendor can update individually)'))
    op.add_column('purchase_orders', sa.Column('expected_ship_date', sa.Date(), nullable=True, comment='When vendor expects to ship goods (updated by vendor)'))
    op.add_column('purchase_orders', sa.Column('expected_arrival_date', sa.Date(), nullable=True, comment='When goods are expected to arrive at warehouse or client (updated by vendor)'))
    op.add_column('sales_orders', sa.Column('order_date', sa.Date(), nullable=True, comment='Date the customer placed the order (from their PO)'))
    op.add_column('sales_orders', sa.Column('due_date', sa.Date(), nullable=True, comment='Overall due date for the entire Sales Order'))
    op.add_column('so_lines', sa.Column('due_date', sa.Date(), nullable=True, comment='Per-line-item due date (from customer PO – each SKU can have a different due date)'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('so_lines', 'due_date')
    op.drop_column('sales_orders', 'due_date')
    op.drop_column('sales_orders', 'order_date')
    op.drop_column('purchase_orders', 'expected_arrival_date')
    op.drop_column('purchase_orders', 'expected_ship_date')
    op.drop_column('po_lines', 'expected_arrival_date')
    op.drop_column('po_lines', 'expected_ship_date')
    op.drop_column('po_lines', 'due_date')
    # ### end Alembic commands ###
