"""add_lead_time_weeks_to_vendor_and_secondary_vendor_to_sku

Revision ID: d8d0bb980271
Revises: 846f1e5b4df9
Create Date: 2026-03-18 14:44:37.011050

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd8d0bb980271'
down_revision: Union[str, None] = '846f1e5b4df9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('skus', sa.Column('secondary_vendor_id', sa.Integer(), nullable=True, comment='Backup vendor used when default vendor cannot fulfil'))
    op.create_foreign_key(None, 'skus', 'vendors', ['secondary_vendor_id'], ['id'])
    op.add_column('vendors', sa.Column('lead_time_weeks', sa.Integer(), nullable=True, comment='Typical manufacturing/delivery lead time in weeks'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('vendors', 'lead_time_weeks')
    op.drop_constraint(None, 'skus', type_='foreignkey')
    op.drop_column('skus', 'secondary_vendor_id')
    # ### end Alembic commands ###
